/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package slidepuzzlegame;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Collections;
import java.util.Comparator;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Slidepuzzlegames extends javax.swing.JFrame {

    /**
     * Creates new form Slidepuzzlegames
     */
    int counter = 0;
    int t=0, minute=0, i=1,Time=0;
    Timer timer;
    Timer timer1;
    String player1name, time1, place;
    DefaultTableModel model;
    
    public Slidepuzzlegames() {
        initComponents();
        counterlable.setText("Moves : 0");
        timelable2.setText("Time : ");
        timelable1.setText("0 : 0");
        Color color = new Color(204,204,255);
        getContentPane().setBackground(color);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    }
    
    public void count(){
        counter++;
        counterlable.setText("Moves : "+ counter);
    }
    
    public void swap(JButton button1, JButton button2){
        String temp = button1.getText();
        button1.setText(button2.getText());
        button2.setText(temp);
    }
    
    public void addPlayer(){
        if(minute!=0){
            Time = ((minute)*60) + (t-1);
            minute--;
        }else{
            Time = (t-1);
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String player1name = playerText.getText();
        model.addRow(new Object[]{ player1name, String.valueOf(Time)});
        sortLeaderboard();
        
    }
    
    public void sortLeaderboard() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Collections.sort(model.getDataVector(), new Comparator<Object>() {
            @Override
            public int compare(Object o1, Object o2) {
                String time1 = (String) ((Vector<?>) o1).get(1);
                String time2 = (String) ((Vector<?>) o2).get(1);
                return Integer.parseInt(time1.trim()) - Integer.parseInt(time2.trim());
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        playerText = new javax.swing.JTextField();
        counterlable = new javax.swing.JLabel();
        timelable2 = new javax.swing.JLabel();
        timelable1 = new javax.swing.JLabel();
        bstart = new javax.swing.JButton();
        bstop = new javax.swing.JButton();
        bnew = new javax.swing.JButton();
        bsolve = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 51, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Slide Puzzle Game");

        b2.setBackground(new java.awt.Color(51, 0, 51));
        b2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("6");
        b2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b2.setContentAreaFilled(false);
        b2.setFocusPainted(false);
        b2.setOpaque(true);
        b2.setPreferredSize(new java.awt.Dimension(50, 50));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(51, 0, 51));
        b3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("7");
        b3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b3.setContentAreaFilled(false);
        b3.setFocusPainted(false);
        b3.setOpaque(true);
        b3.setPreferredSize(new java.awt.Dimension(50, 50));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(51, 0, 51));
        b4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setText("13");
        b4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b4.setContentAreaFilled(false);
        b4.setFocusPainted(false);
        b4.setOpaque(true);
        b4.setPreferredSize(new java.awt.Dimension(50, 50));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(51, 0, 51));
        b8.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b8.setForeground(new java.awt.Color(255, 255, 255));
        b8.setText("2");
        b8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b8.setContentAreaFilled(false);
        b8.setFocusPainted(false);
        b8.setOpaque(true);
        b8.setPreferredSize(new java.awt.Dimension(50, 50));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(51, 0, 51));
        b7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 255, 255));
        b7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b7.setContentAreaFilled(false);
        b7.setFocusPainted(false);
        b7.setOpaque(true);
        b7.setPreferredSize(new java.awt.Dimension(50, 50));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(51, 0, 51));
        b6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b6.setForeground(new java.awt.Color(255, 255, 255));
        b6.setText("14");
        b6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b6.setContentAreaFilled(false);
        b6.setFocusPainted(false);
        b6.setOpaque(true);
        b6.setPreferredSize(new java.awt.Dimension(50, 50));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(51, 0, 51));
        b5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 255, 255));
        b5.setText("12");
        b5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b5.setContentAreaFilled(false);
        b5.setFocusPainted(false);
        b5.setOpaque(true);
        b5.setPreferredSize(new java.awt.Dimension(50, 50));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(51, 0, 51));
        b1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("1");
        b1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b1.setContentAreaFilled(false);
        b1.setFocusPainted(false);
        b1.setOpaque(true);
        b1.setPreferredSize(new java.awt.Dimension(50, 50));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b10.setBackground(new java.awt.Color(51, 0, 51));
        b10.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b10.setForeground(new java.awt.Color(255, 255, 255));
        b10.setText("4");
        b10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b10.setContentAreaFilled(false);
        b10.setFocusPainted(false);
        b10.setOpaque(true);
        b10.setPreferredSize(new java.awt.Dimension(50, 50));
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        b13.setBackground(new java.awt.Color(51, 0, 51));
        b13.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b13.setForeground(new java.awt.Color(255, 255, 255));
        b13.setText("5");
        b13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b13.setContentAreaFilled(false);
        b13.setFocusPainted(false);
        b13.setOpaque(true);
        b13.setPreferredSize(new java.awt.Dimension(50, 50));
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        b11.setBackground(new java.awt.Color(51, 0, 51));
        b11.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b11.setForeground(new java.awt.Color(255, 255, 255));
        b11.setText("11");
        b11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b11.setContentAreaFilled(false);
        b11.setFocusPainted(false);
        b11.setOpaque(true);
        b11.setPreferredSize(new java.awt.Dimension(50, 50));
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b16.setBackground(new java.awt.Color(51, 0, 51));
        b16.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b16.setForeground(new java.awt.Color(255, 255, 255));
        b16.setText("8");
        b16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b16.setContentAreaFilled(false);
        b16.setFocusPainted(false);
        b16.setOpaque(true);
        b16.setPreferredSize(new java.awt.Dimension(50, 50));
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });

        b15.setBackground(new java.awt.Color(51, 0, 51));
        b15.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b15.setForeground(new java.awt.Color(255, 255, 255));
        b15.setText("9");
        b15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b15.setContentAreaFilled(false);
        b15.setFocusPainted(false);
        b15.setOpaque(true);
        b15.setPreferredSize(new java.awt.Dimension(50, 50));
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });

        b14.setBackground(new java.awt.Color(51, 0, 51));
        b14.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b14.setForeground(new java.awt.Color(255, 255, 255));
        b14.setText("10");
        b14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b14.setContentAreaFilled(false);
        b14.setFocusPainted(false);
        b14.setOpaque(true);
        b14.setPreferredSize(new java.awt.Dimension(50, 50));
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });

        b12.setBackground(new java.awt.Color(51, 0, 51));
        b12.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b12.setForeground(new java.awt.Color(255, 255, 255));
        b12.setText("15");
        b12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b12.setContentAreaFilled(false);
        b12.setFocusPainted(false);
        b12.setOpaque(true);
        b12.setPreferredSize(new java.awt.Dimension(50, 50));
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(51, 0, 51));
        b9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 255, 255));
        b9.setText("3");
        b9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        b9.setContentAreaFilled(false);
        b9.setFocusPainted(false);
        b9.setOpaque(true);
        b9.setPreferredSize(new java.awt.Dimension(50, 50));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 17)); // NOI18N
        jLabel2.setText("Player Name :");

        playerText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerTextActionPerformed(evt);
            }
        });

        counterlable.setFont(new java.awt.Font("Segoe UI Black", 1, 17)); // NOI18N
        counterlable.setText("Moves : 0");

        timelable2.setFont(new java.awt.Font("Segoe UI Black", 1, 17)); // NOI18N
        timelable2.setForeground(new java.awt.Color(0, 0, 0));
        timelable2.setText("Time :");

        timelable1.setFont(new java.awt.Font("Segoe UI Black", 1, 17)); // NOI18N
        timelable1.setText("0 : 0");

        bstart.setBackground(new java.awt.Color(51, 204, 255));
        bstart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bstart.setForeground(new java.awt.Color(0, 0, 0));
        bstart.setText("Start");
        bstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstartActionPerformed(evt);
            }
        });

        bstop.setBackground(new java.awt.Color(51, 204, 255));
        bstop.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bstop.setForeground(new java.awt.Color(0, 0, 0));
        bstop.setText("Stop");
        bstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstopActionPerformed(evt);
            }
        });

        bnew.setBackground(new java.awt.Color(255, 102, 51));
        bnew.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bnew.setForeground(new java.awt.Color(0, 0, 0));
        bnew.setText("Restart");
        bnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnewActionPerformed(evt);
            }
        });

        bsolve.setBackground(new java.awt.Color(255, 102, 51));
        bsolve.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        bsolve.setForeground(new java.awt.Color(0, 0, 0));
        bsolve.setText("Solve");
        bsolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsolveActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 17)); // NOI18N
        jLabel3.setText("Leaderboard");

        jTable1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Player Name", "Time (seconds)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bnew)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bsolve))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(playerText, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(counterlable, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(timelable2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(timelable1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(bstart, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(bstop, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(44, 44, 44))))
                    .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(counterlable, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(timelable1)
                                    .addComponent(timelable2))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bstart)
                                    .addComponent(bstop))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bnew, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bsolve)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if(evt.getSource()== b3){
            String s = b3.getText();
            if(b2.getText().equals("")){b2.setText(s); b3.setText("");}
            else if(b4.getText().equals("")){b4.setText(s); b3.setText("");}
            else if(b6.getText().equals("")){b6.setText(s); b3.setText("");}
            count();
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(evt.getSource()== b1){
            String s = b1.getText();
            if(b8.getText().equals("")){b8.setText(s); b1.setText("");}
            else if(b2.getText().equals("")){b2.setText(s); b1.setText("");}
            count();
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        if(evt.getSource()== b10){
            String s = b10.getText();
            if(b7.getText().equals("")){b7.setText(s); b10.setText("");}
            else if(b9.getText().equals("")){b9.setText(s); b10.setText("");}
            else if(b11.getText().equals("")){b11.setText(s); b10.setText("");}
            else if(b15.getText().equals("")){b15.setText(s); b10.setText("");}
            count();
        }
    }//GEN-LAST:event_b10ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        if(evt.getSource()== b13){
            String s = b13.getText();
            if(b12.getText().equals("")){b12.setText(s); b13.setText("");}
            else if(b14.getText().equals("")){b14.setText(s); b13.setText("");}
            count();
        }
    }//GEN-LAST:event_b13ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        if(evt.getSource()== b11){
            String s = b11.getText();
            if(b6.getText().equals("")){b6.setText(s); b11.setText("");}
            else if(b10.getText().equals("")){b10.setText(s); b11.setText("");}
            else if(b12.getText().equals("")){b12.setText(s); b11.setText("");}
            else if(b14.getText().equals("")){b14.setText(s); b11.setText("");}
            count();
        }
    }//GEN-LAST:event_b11ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        if(evt.getSource()== b16){
            String s = b16.getText();
            if(b9.getText().equals("")){b9.setText(s); b16.setText("");}
            else if(b15.getText().equals("")){b15.setText(s); b16.setText("");}
            count();
            
        }
        
        if(b1.getText().equals("1")&& b2.getText().equals("2")&& b3.getText().equals("3")&& b4.getText().equals("4")&& b5.getText().equals("5")
           && b6.getText().equals("6")&& b7.getText().equals("7")&& b8.getText().equals("8")&& b9.getText().equals("9")&& b10.getText().equals("10")
           && b11.getText().equals("11")&& b12.getText().equals("12")&& b13.getText().equals("13")&& b14.getText().equals("14")&& b15.getText().equals("15")
           && b16.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Congratulations! You won");}
    }//GEN-LAST:event_b16ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
        if(evt.getSource()== b15){
            String s = b15.getText();
            if(b10.getText().equals("")){b10.setText(s); b15.setText("");}
            else if(b14.getText().equals("")){b14.setText(s); b15.setText("");}
            else if(b16.getText().equals("")){b16.setText(s); b15.setText("");}
            count();
        }
    }//GEN-LAST:event_b15ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        if(evt.getSource()== b14){
            String s = b14.getText();
            if(b11.getText().equals("")){b11.setText(s); b14.setText("");}
            else if(b13.getText().equals("")){b13.setText(s); b14.setText("");}
            else if(b15.getText().equals("")){b15.setText(s); b14.setText("");}
            count();
        }
    }//GEN-LAST:event_b14ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        if(evt.getSource()== b12){
            String s = b12.getText();
            if(b5.getText().equals("")){b5.setText(s); b12.setText("");}
            else if(b11.getText().equals("")){b11.setText(s); b12.setText("");}
            else if(b13.getText().equals("")){b13.setText(s); b12.setText("");}
            count();
        }
    }//GEN-LAST:event_b12ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if(evt.getSource()== b9){
            String s = b9.getText();
            if(b8.getText().equals("")){b8.setText(s); b9.setText("");}
            else if(b10.getText().equals("")){b10.setText(s); b9.setText("");}
            else if(b16.getText().equals("")){b16.setText(s); b9.setText("");}
            count();
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if(evt.getSource()== b2){
            String s = b2.getText();
            if(b1.getText().equals("")){b1.setText(s); b2.setText("");}
            else if(b3.getText().equals("")){b3.setText(s); b2.setText("");}
            else if(b7.getText().equals("")){b7.setText(s); b2.setText("");}
            count();
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if(evt.getSource()== b4){
            String s = b4.getText();
            if(b3.getText().equals("")){b3.setText(s); b4.setText("");}
            else if(b5.getText().equals("")){b5.setText(s); b4.setText("");}
            count();
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if(evt.getSource()== b5){
            String s = b5.getText();
            if(b12.getText().equals("")){b12.setText(s); b5.setText("");}
            else if(b4.getText().equals("")){b4.setText(s); b5.setText("");}
            else if(b6.getText().equals("")){b6.setText(s); b5.setText("");}
            count();
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if(evt.getSource()== b6){
            String s = b6.getText();
            if(b3.getText().equals("")){b3.setText(s); b6.setText("");}
            else if(b5.getText().equals("")){b5.setText(s); b6.setText("");}
            else if(b7.getText().equals("")){b7.setText(s); b6.setText("");}
            else if(b11.getText().equals("")){b11.setText(s); b6.setText("");}
            count();
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if(evt.getSource()== b7){
            String s = b7.getText();
            if(b2.getText().equals("")){b2.setText(s); b7.setText("");}
            else if(b6.getText().equals("")){b6.setText(s); b7.setText("");}
            else if(b8.getText().equals("")){b8.setText(s); b7.setText("");}
            else if(b10.getText().equals("")){b10.setText(s); b7.setText("");}
            count();
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if(evt.getSource()== b8){
            String s = b8.getText();
            if(b1.getText().equals("")){b1.setText(s); b8.setText("");}
            else if(b7.getText().equals("")){b7.setText(s); b8.setText("");}
            else if(b9.getText().equals("")){b9.setText(s); b8.setText("");}
            count();
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void bnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnewActionPerformed
        if(evt.getSource()== bnew){
            b1.setText("1");
            b2.setText("6");
            b3.setText("7");
            b4.setText("13");
            b5.setText("12");
            b6.setText("14");
            b7.setText("");
            b8.setText("2");
            b9.setText("3");
            b10.setText("4");
            b11.setText("11");
            b12.setText("15");
            b13.setText("5");
            b14.setText("10");
            b15.setText("9");
            b16.setText("8");
            counter = 0;
            counterlable.setText("Moves : 0");
            timelable2.setText("Time : ");
            timelable1.setText("0 : 0");
            t=0;
            playerText.setText(" ");           
           
        }
    }//GEN-LAST:event_bnewActionPerformed

    private void bstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstartActionPerformed
        timer = new Timer(1000,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                timelable1.setText(String.valueOf(minute)+" : "+String.valueOf(t));
                t++;
                if(t==60){
                    minute++;
                    t=0;
                }
            }
        }); 
        timer.start();
        player1name = playerText.getText();
        if(player1name.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter player name");
            timer.stop();
            timelable1.setText("0 : 0");
            t=0;
        }
    }//GEN-LAST:event_bstartActionPerformed

    private void bstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstopActionPerformed
        timer.stop();
        if(!player1name.isEmpty()){
            addPlayer();
        }
    }//GEN-LAST:event_bstopActionPerformed

    private void bsolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsolveActionPerformed
        if(evt.getSource()== bsolve){    
            b1.setText("1");
            b2.setText("2");
            b3.setText("3");
            b4.setText("4");
            b5.setText("5");
            b6.setText("6");
            b7.setText("7");
            b8.setText("8");
            b9.setText("9");
            b10.setText("10");
            b11.setText("11");
            b12.setText("12");
            b13.setText("13");
            b14.setText("14");
            b15.setText("15");
            b16.setText("");
        }         
    }//GEN-LAST:event_bsolveActionPerformed

    private void playerTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Slidepuzzlegames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Slidepuzzlegames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Slidepuzzlegames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Slidepuzzlegames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Slidepuzzlegames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bnew;
    private javax.swing.JButton bsolve;
    private javax.swing.JButton bstart;
    private javax.swing.JButton bstop;
    private javax.swing.JLabel counterlable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField playerText;
    private javax.swing.JLabel timelable1;
    private javax.swing.JLabel timelable2;
    // End of variables declaration//GEN-END:variables
}
